name: enrsancar1
on:
  workflow_dispatch:
  issues:
    types: [opened]
  project_card:
    types: [moved]    
jobs:
  enrique:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :sparkles: Enrique Sanchez :sparkles:
