name: enrsancar1
on:
  workflow_dispatch:
  issues:
    types: [opened]
  project_card:
    types: [moved]    
jobs:
  enrique:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '# Hola Enrique.'
          pr-message: ''
